### PR TITLE
Fixing version check to handle case without channel or date (ie 0.11.1)

### PR DESCRIPTION
**Pull request by shawnbissell**

### CODE REVIEW

**Comment by shawnbissell** [comment]
looks like I got another change in this same PR by accident

**Comment by Pogman** [comment]
Ok thanks... funny bug this given the amount of complexity everywhere else, sods law :)

The uploader status to NS stuff is a bit prototypey at the moment and needs a bit more consideration due to many users using multiple uploaders etc. Also the battery charge status notification should default off as there may be issues for some devices that go in and out of 100% all the time while charging and there may be other unknown inconsistencies between android version and brands. I'm also wary of settings overload for users and need to consider these parts too.

**Comment by shawnbissell** [comment]
Ok I defaulted the System Status messages back off again. I was thinking there could be a setting for each one of those messages and the critical battery low message might be default on?

**Comment by shawnbissell** [comment]
Added the Uploader USB Errors configuration option and cleaned up the Nighscout advanced preferences :)

**Comment by Pogman** [comment]
I can merge this as is and sure see how it feels. Don't know about moving that TTL item as it's tightly related to keeping alerts/status noise in NS minimal and hopefully a user senses that relationship. But hey-ho it can be adjusted.

**Pull request merged**
